import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "iWatch Gallery Example",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        // style={{ backgroundColor: `var(--color-iwatch-blue)` }}
        className="bg-linear-to-r from-iwatch-gradient-from to-iwatch-gradient-to antialiased w-full h-screen place-items-center place-content-center"
      >
        {children}
      </body>
    </html>
  );
}
